version: "3.9"
services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      - POSTGRES_USER=hacklahoma
      - POSTGRES_PASSWORD=p4ssw0rd
      - POSTGRES_DB=reggie
    ports:
      - 5435:5435
    expose:
      - 5435
    command: -p 5435 
  server:
    restart: unless-stopped
    build: ./server/
    ports:
      - 3333:3333
    volumes:
      - .:/src/server/
      - /src/node_modules
    environment:
      - PORT=3333
      - HOST=0.0.0.0
      - NODE_ENV=development
      - APP_KEY=wCgLV0fOnLjNOX-U1XF57yubSrBv-C3y
      - DB_CONNECTION=pg
      - PG_HOST=postgres
      - PG_PORT=5435
      - PG_USER=hacklahoma
      - PG_PASSWORD=p4ssw0rd
      - PG_DB_NAME=reggie
    depends_on:
      - postgres
  client:
    restart: unless-stopped
    build: ./client/
    ports:
      - 3000:3000
    volumes:
      - .:/src/client/
      - /src/node_modules
    environment:
      - BACKEND_CONNECTION=localhost:3333
    depends_on:
      - server
