version: "3.9"
services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      - POSTGRES_USER=hacklahoma
      - POSTGRES_PASSWORD=p4ssw0rd
      - POSTGRES_DB=reggie
    ports:
      - 5430:5430
    expose:
      - 5430
    command: -p 5430
  server:
    restart: unless-stopped
    build: ./server/
    ports:
      - 3333:3333
    volumes:
      - ./server:/app/
      - /app/node_modules
    environment:
      - PORT=3333
      - HOST=0.0.0.0
      - NODE_ENV=development
      - APP_KEY=wCgLV0fOnLjNOX-U1XF57yubSrBv-C3y
      - DB_CONNECTION=pg
      - PG_HOST=localhost
      - PG_PORT=5430
      - PG_USER=hacklahoma
      - PG_PASSWORD=p4ssw0rd
      - PG_DB_NAME=reggie
      - GOOGLE_CLIENT_ID=clientId
      - GOOGLE_CLIENT_SECRET=clientSecret
      - DISCORD_CLIENT_ID=clientId
      - DISCORD_CLIENT_SECRET=clientSecret
      - SMTP_HOST=localhost
      - SMTP_PORT=587
      - SMTP_USERNAME=<username>
      - SMTP_PASSWORD=<password>
      - CACHE_VIEWS=false
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - postgres
  client:
    restart: unless-stopped
    build: ./client/
    ports:
      - 3000:3000
    volumes:
      - ./client:/app/
      - /app/node_modules
    environment:
      - BACKEND_CONNECTION=localhost:3333
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
